### ISSUE TITLE
Allow to choose coordinates and not protocol in xmipp picking (step 2)..

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion-em-xmipp#190]
From @azazellochg : 

> Another issue is that if I do manual picking (step 1) few times, producing several outputCoordinates, then in step2 I can select only outputCoordinates as input and not outputCoordinates2, outputCoordinates3 etc.

**Comment by dmaluenda** [comment]
Hi @pconesa and @azazellochg, and thanks.

I think that is not exacly in the descibed way. Xmipp-autoPicking protocol has xmipp-mamualPicking protocol as input, instead of a setOfCoordinates. Then, the autopinking is done using all the machine learning recovered data placed at manualPicking/extra. This means that the last state of the manual picking is used.

**Comment by azazellochg** [comment]
Hi @dmaluenda , you are right. Thanks!
