### ISSUE TITLE
Volume protocols for tomography

### ISSUE THREAD

**Issue by EstrellaFG** [I2PC/scipion-em-xmipp#203]
Protocols `crop/resize volumes`, `preprocess volumes` and `filter volumes` are very useful in tomography because they can take as input a Tomogram or Subtomogram objects (because this objects inherit from Volume).
However, the output is a SetOfVolumes always. To use this protocols properly in tomography, we need the output be the same class of objects as the input.

**Comment by dmaluenda** [comment]
I've run the Crop/Resize test and I see 3 cases where the input is a SetOfVolumes and other 3 where the input is a single Volume. For the first cases the output are SetOfVolumes while, for the last, they are single Volumes.

Even thought, if you have a SetOfVolumes while you want to use a single Volume in a next protocol, the objects' browser should show you the SetOfVolumes with an arrow in order to spread the items and enabling to select a certain item.

Find below a screenshot with the TestCropResizeVolumes project showing (in the summary) that output is a single Volume when the input is a single Volume; and a objects' browser finding Volumes and SetOfVolumes (input for the cropResizeVolume protocol) where user can select a certain item of a SetOfVolumes.

I don't know how it works in tomography and I think that should work in the same way. So, please, show me the behavior that you gets.

Thanks!

![Captura de pantalla 2020-03-20 a las 11 21 53](https://user-images.githubusercontent.com/30288932/77155539-fb7e7580-6a9d-11ea-9fb0-8d0a121ae394.png)

**Comment by EstrellaFG** [comment]
Thanks for the quick response! But I think I didn't explain my self properly... The problem is that when the input is a SetOfSubtomograms or a SetOfTomograms, the output is a SetOfVolumes (in both cases). So as this output is not a tomogram or subtomogram it can not be used as input of any protocol that works with tomograms or subtomograms. So, what we need is that if input is subtomogram (or setOfSubtomograms), the output be a subtomogram (or setOfsubtomograms) also, and the same for tomograms. @pconesa suggested that this can be done in Scipion3.

**Comment by dmaluenda** [comment]
Got it!

I will have a look.

Thanks!

**Comment by pconesa** [comment]
I think we can make those "generic protocols" to create the output as the same type os the input set using the new Set._create() method, asking the set to create a copy of it so the protocol can be agnostic of the type.

**Comment by EstrellaFG** [comment]
Solved in PR https://github.com/I2PC/scipion-em-xmipp/pull/229
