### ISSUE TITLE
movie max shift issue

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion-em-xmipp#40]
I dont know how xmipp does drift estimation, but mc2 returns frame shifts with the first frame as reference. Meaning that the last frame of the movie will accumulate large shifts but it doesnt mean that the whole movie is bad. The max shift protocol (type=by_frame) simply rejects the movie because last frame has large shifts. This is not good..
I know that unblur, mc2, relion and xmipp all produce different output so maybe we should try to standardize it before putting into movie.alignment?

Also, the output are only non DW movies/mic, I want to have DW sets as well.

**Comment by dmaluenda** [comment]
Hi @azazellochg, I checked that MotionCor2 and Xmipp are returning shifts as coordinates on a certain framework, instead of returning partial drifts. In fact, the general shift-chart generator is assuming the same (it plots what it's getting). So, I think this should be the standard. And yes, that means some frame may accumulate a large shift but doing it in a smooth way. However, this doesn't means that the MovieMaxShift protocol will reject the movie for that reason.

At least if 'RejectByFrame' is selected, since it is asserting the drifts between frames instead of directly reading the shifts values.

_piece of code:_
https://github.com/I2PC/scipion-em-xmipp/blob/c12a1115f268ec77edd34bf5c84e6ffad256a818/xmipp3/protocols/protocol_movie_max_shift.py#L142-L148

If  'RejectByMovie' is selected, then a large accumulated shift means a large whole drift and if it's large than the threshold it should be rejected...

If you don't care if a large total travel is walk if this travel was done in a smooth way, make sure that the 'Reject by Frame' is selected.


Regarding the Dose-Weighted output, I've include it in PR https://github.com/I2PC/scipion-em-xmipp/pull/91 .
Thanks to point out this!!

**Comment by azazellochg** [comment]
Hi @dmaluenda, indeed I must have missed np.diff function, thank you for pointing this out!
