### ISSUE TITLE
xmipp auto picking

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion-em-xmipp#451]
When picking on "other" set, the output set of coordinates is pointing to the setof micrographs pointed by the manual picking "Same" and not the "other" (new one)

**Comment by MartinSalinas98** [comment]
I just checked this issue using the test project created by running `scipion3 tests xmipp3.tests.test_protocols_xmipp_mics.TestXmippAutomaticPicking`, but changing the branch that includes manual picking to only point to one micrograph file instead of all of them (being that one a different one from the other branch), and this error didn't happen, the coordinates in the output of the automatic picking point to the correct micrograph (the "other").

Since this issue is old, it has probably been fixed at some point.
