### ISSUE TITLE
"xmipp3 - estimate local defocus" protocol fails

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion-em-xmipp#457]
Protocol fails in Scipion v3.0.8 - 3.0.16 (core) with this error message:

File "/appl/soft/math/scipion/3.0.7/.scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_local_ctf.py", line 123, in createOutputStep
00056:       readSetOfParticles(self._getExtraPath('output_imgs.xmd'), outputSet,  extraLabels=[emlib.MDL_CTF_DEFOCUS_CHANGE])
00057:   AttributeError: module 'pwem.emlib' has no attribute 'MDL_CTF_DEFOCUS_CHANGE'
00058:   Protocol failed: module 'pwem.emlib' has no attribute 'MDL_CTF_DEFOCUS_CHANGE'

**Comment by DStrelak** [comment]
Hi @JuhaHuiskonen , 

this looks like a problem in interaction with Xmipp.
Please check that you do NOT see an error message in the terminal regarding missing image library during Scipion project opening.
If you do, please install the latest version of Xmipp (e.g. via the Plugin Manager).

**Comment by delarosatrevin** [comment]
This might be an Xmipp installation issue, but I don't think it is the case because @JuhaHuiskonen has been using the installation in the cluster. Another possibility is that the protocol is using development labels that are not in the stable version of xmipp binaries. Could you check that opiont @DStrelak ?

**Comment by DStrelak** [comment]
That label is present in Xmipp for a long time: https://github.com/I2PC/xmippCore/blame/devel/core/metadata_label.h#L131

@JuhaHuiskonen Is this issue still active?
