### ISSUE TITLE
xmipptomo does not run in buildbot cause by  viewer here...

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion-em-xmipp#716]
http://scipion-test.cnb.csic.es:9980/#/builders/46/builds/270

There, the strucmap viewer forces matlotlib to use tkAgg and since buildbot runs in headless mode it fails.

Maybe the line:

matplotlib.use("TkAgg")

Can be removed?

**Comment by DavidHerreros** [comment]
When the viewer was made, that line was needed to execute the viewer and its interactive part. However, maplotlib version has been updated in Scipion since that moment, so it might be that is already handled correctly without it.

The protocol using that viewer is not heavily used, so I would suggest to comment that line so it does not block buildbot. In the meantime, I can check if it works fine with the suggested modification, would that be fine?

**Comment by albertmena** [comment]
> When the viewer was made, that line was needed to execute the viewer and its interactive part. However, maplotlib version has been updated in Scipion since that moment, so it might be that is already handled correctly without it.
> 
> The protocol using that viewer is not heavily used, so I would suggest to comment that line so it does not block buildbot. In the meantime, I can check if it works fine with the suggested modification, would that be fine?

Perfect, I comment it, and please check that works fine

**Comment by albertmena** [comment]
PR to fix it: https://github.com/I2PC/scipion-em-xmipp/pull/763
